web:
  build: .
  volumes:
    - .:/schedulr
  ports:
    - "3000:3000"
  # links:
  #    - db
  env_file:
    - '.env.web'
# db:
#   image: library/mysql:5.6.29
#   ports:
#     - "3307:3306"
#   env_file:
#     - '.env.db'
