web:
  build: .
  volumes:
    - .:/schedulr
  ports:
    - "3000:3000"
  environment:
    RAILS_ENV: development
    DATABASE_URL: mysql2://root:root@mysql/rails
  links:
    - "mysql:mysql"
mysql:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: rails
